Clicker/urls.py
from django.urls import path
from Clicker import views
from django.contrib.auth.decorators import login_required

app_name = 'clicker'

urlpatterns = [
    path('play/', login_required(views.clicker_view), name='play'),
    path('call_click/', views.call_click, name='call_click'),
    path('onload_image/', views.onload_image, name='onload'),
]

HentaiClicker/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from Clicker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='users')),
    path('clicker/', include('Clicker.urls', namespace='clicker'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from users.views import UserRegisterView, UserLoginView, UserWelcomeView
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('welcome/', login_required(UserWelcomeView.as_view()), name='welcome'),
]

Clicker/models.py
from django.db import models

import users.models


class Tentacles(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, default='Tentacle')
    cost = models.IntegerField(default=0)
    power = models.IntegerField(default=1)
    image = models.ImageField(upload_to='tentacles_images', null=True, blank=True, default=None)

    class Meta:
        verbose_name_plural = verbose_name = 'Тентакли'

    def __str__(self):
        return f'{self.name}'


class Results(models.Model):
    user = models.ForeignKey(to=users.models.User, on_delete=models.CASCADE)
    tentacle = models.ForeignKey(Tentacles, on_delete=models.CASCADE)
    tentacle_quantity = models.PositiveIntegerField(default=0)
    score = models.IntegerField(default=0)
    click_power = models.IntegerField(default=1)
    level = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

    def __str__(self):
        return f'Результаты {self.user.username}'

    def click(self):
        self.score += self.click_power
        return self

    def check_level(self):
        check_points = [50000, 250000, 6250000]
        for i in range(1, 4):
            if self.score >= check_points[i-1] and self.level < i:
                self.level = i

Clicker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from rest_framework.decorators import api_view
from django.http import HttpResponse, HttpResponseRedirect
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework import viewsets
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from Clicker.models import Tentacles, Results


def clicker_view(request):
    context = {
        'results': Results.objects.filter(user=request.user),
        'tentacles': Tentacles.objects.all()
    }
    return render(request, 'clicker.html', context)


def onload_image(request):
    result = Results.objects.get(user=request.user)
    return HttpResponseRedirect(result)


def call_click(request):
    result = Results.objects.get(user=request.user)
    result.click()
    result.check_level()
    result.save()
    return HttpResponseRedirect(request.path_info)

# class ClickerPlayView(ListView):
#     model = Results
#     template_name = 'clicker.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(ClickerPlayView, self).get_context_data()
#         context['results_list'] = Results.objects.filter(user=self.request.user)
#         return context

# @api_view(['GET'])
# @login_required
# def onload_image(request):
#     user = UserData.objects.get(user=request.user)
#     return Response({'user': UserSerializer(user).data})
#
#
# @api_view(['GET'])
# def call_click(request):
#     user = UserData.objects.get(user=request.user)
#     user.click()
#     user.check_level()
#     user.save()
#
#     return Response({'user': UserSerializer(user).data})
# @api_view(['GET'])
# @login_required
# def update_power1(request):
#     user = UserData.objects.get(user=request.user)
#
#     # Проверяем, что хватает денег. Если не хватает, ничего не делаем
#     if user.score < user.tentacle1_cost:
#         return Response({'user': UserSerializer(user).data})
#
#     # Если денег всё-таки хватило, то
#     user.tentacle1_count += 1                               # Количество тентаклей увеличиваем на 1
#     user.click_power += 1                                   # Еще и силу клика увеличиваем
#     user.score -= user.tentacle1_cost                       # Стоимость тентаклины вычитаем из Счёта
#     user.tentacle1_cost = round(user.tentacle1_cost * 1.5)  # Делаем новую стоимость тентаклины
#     user.save()                                             # Сохраняем
#
#     return Response({'user': UserSerializer(user).data})    # Внизу всё то же самое
#
#
# @api_view(['GET'])
# @login_required
# def update_power2(request):
#     user = UserData.objects.get(user=request.user)
#
#     if user.score < user.tentacle2_cost:
#         return Response({'user': UserSerializer(user).data})
#
#     user.tentacle2_count += 1
#     user.click_power += 5
#     user.score -= user.tentacle2_cost
#     user.tentacle2_cost = round(user.tentacle2_cost * 1.5)
#     user.save()
#
#     return Response({'user': UserSerializer(user).data})
#
#
# @api_view(['GET'])
# @login_required
# def update_power3(request):
#     user = UserData.objects.get(user=request.user)
#
#     if user.score < user.tentacle3_cost:
#         return Response({'user': UserSerializer(user).data})
#
#     user.tentacle3_count += 1
#     user.click_power += 25
#     user.score -= user.tentacle3_cost
#     user.tentacle3_cost = round(user.tentacle3_cost * 1.5)
#     user.save()
#
#     return Response({'user': UserSerializer(user).data})
#
#
# @api_view(['GET'])
# @login_required
# def update_power4(request):
#     user = UserData.objects.get(user=request.user)
#
#     if user.score < user.tentacle4_cost:
#         return Response({'user': UserSerializer(user).data})
#
#     user.tentacle4_count += 1
#     user.click_power += 125
#     user.score -= user.tentacle4_cost
#     user.tentacle4_cost = round(user.tentacle4_cost * 1.5)
#     user.save()
#
#     return Response({'user': UserSerializer(user).data})
#
#
# @api_view(['GET'])
# @login_required
# def update_power5(request):
#     user = UserData.objects.get(user=request.user)
#
#     if user.score < user.tentacle5_cost:
#         return Response({'user': UserSerializer(user).data})
#
#     user.tentacle5_count += 1
#     user.click_power += 625
#     user.score -= user.tentacle5_cost
#     user.tentacle5_cost = round(user.tentacle5_cost * 1.5)
#     user.save()
#
#     return Response({'user': UserSerializer(user).data})
#
#
# # Эта параша(иначе её не назвать: страшная и воняет) отвечает за вывод циферок на страничку

templates/clicker.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href='{% static 'clicker/hentai_style.css' %}'>
    <title>Hentai Clicker</title>
</head>
<body onload="onload_image()">
    <div style="width: 100%;overflow:auto;">
        <div class="actual-gameplay" id="actual-gameplay" onclick="location.href='{% url 'clicker:call_click' %}'">
            <p class="score">Hits: <span id="score"> {{ results.get.score }}</span></p>
            <img class="girl" id="girl"/>
            <p class="stage" id="stage"></p>
        </div>
        <div class="bar">
            <p class="HPC1">Hits Per Click:</p>
            <br>
            <p class="HPC2" id="HPC">{{ results.get.click_power }}</p>
            <p class="tentacle-shop">Tentacle Shop</p>
                <div class="tentacle">
                    {% for tentacle in tentacles.values %}
                    <button class="tentacle-design" id="tentacle" onclick="update_power(1)">
                        <p class="tentacle-name"> {{ tentacle.name }}</p>
                        <p class="tentacle-price">Price: <span id="tentacle_cost">{{ tentacle.cost }}</span></p>
                        <img src='{% get_media_prefix %}{{ tentacle.image }}' class="tentIMG" alt="">
                        <p class="tentacle-count">x<span id="tentacle1_count">0</span></p>
                    </button>
                    {% endfor %}
                </div>
        </div>
    </div>
    <script src="{% static 'clicker/hentaiJS.js' %}"></script>
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href='{% static 'login/login_style.css' %}'>
    <title>Авторизация в Hentai Clicker</title>
</head>
<body>
<div class="rectangle">
    <p class="login">Авторизация</p>
    <form class="forms" action="{% url 'users:login' %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button">
    </form>
    <p class="nonregistered"><a href="{% url 'users:register' %}">Не зарегистрирован?</a></p>
</div>
</body>
</html>

templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href='{% static 'register/register_style.css' %}'>
    <title>Регистрация в Hentai Clicker</title>
</head>
<body>
<div class="rectangle">
        <p class="registration">Регистрация</p>
        {% if form.errors %}
            <p>{{ form.errors }}</p>
        {% endif %}
        <form class="forms" action="{% url 'users:register' %}" method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button" type="submit">
        </form>
        <p class="registered"><a href="{% url 'users:login' %}">Зарегистрирован?</a></p>
</div>
<div class="blur"></div>
</body>
</html>

templates/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href='{% static 'welcome/welcome_style.css' %}'>
    <title>Welcome</title>
</head>
<body>
    <div class="upper-txt">
        Welcome <br>to my <br>Hentai Clicker, <br> {{ user.get_username }}
    </div>
    <div class="logout-button">
        <a href="{% url 'users:logout' %}" class="href-decoration">Logout</a>
    </div>
    <div class="start-button">
        <a href="{% url 'clicker:play' %}" class="href-decoration">Start</a>
    </div>
    <div class="author">
        Author - Bulat Valiev
    </div>
</body>
</html>